/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tictactoe;

/**
 *
 * @author TraderG
 */
public class HistoryPage extends javax.swing.JFrame {

    /**
     * Creates new form HistoryPage
     */
    public HistoryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PlayerProfile3 = new javax.swing.JLabel();
        PlayerProfile4 = new javax.swing.JLabel();
        PlayerProfile5 = new javax.swing.JLabel();
        PlayerProfile6 = new javax.swing.JLabel();
        PlayerProfile7 = new javax.swing.JLabel();
        PlayerProfile8 = new javax.swing.JLabel();
        PlayerProfile9 = new javax.swing.JLabel();
        PlayerProfile10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 850));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("History");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, 60));

        PlayerProfile3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        PlayerProfile4.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 770, -1, -1));

        PlayerProfile5.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 440, -1, -1));

        PlayerProfile6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 440, -1, -1));

        PlayerProfile7.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        PlayerProfile8.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        PlayerProfile9.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, -1, -1));

        PlayerProfile10.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerProfile10;
    private javax.swing.JLabel PlayerProfile3;
    private javax.swing.JLabel PlayerProfile4;
    private javax.swing.JLabel PlayerProfile5;
    private javax.swing.JLabel PlayerProfile6;
    private javax.swing.JLabel PlayerProfile7;
    private javax.swing.JLabel PlayerProfile8;
    private javax.swing.JLabel PlayerProfile9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
