/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tictactoe;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.SwingUtilities;
/**
 *
 * @author TraderG
 */
public class TicTacToePage extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToePage
     */
    public TicTacToePage() {
        initComponents();
        setLookAndFeel();
        setLocationRelativeTo(null);
    }

    private void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
	private static final String DB_URL = "jdbc:mysql://localhost:3306/tictactoe_db?zeroDateTimeBehavior=CONVERT_TO_NULL";
	private static final String DB_USER = "root";
	private static final String DB_PASSWORD = "admin123";

	private int getOrAddPlayer(String playerName) {
		try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
			// Check if player exists
			PreparedStatement selectStmt = conn.prepareStatement("SELECT player_id FROM players WHERE player_name = ?");
			selectStmt.setString(1, playerName);
			ResultSet rs = selectStmt.executeQuery();
			if (rs.next()) {
				return rs.getInt("player_id");
			}

			// Add new player
			PreparedStatement insertStmt = conn.prepareStatement("INSERT INTO players (player_name) VALUES (?)", Statement.RETURN_GENERATED_KEYS);
			insertStmt.setString(1, playerName);
			insertStmt.executeUpdate();
			rs = insertStmt.getGeneratedKeys();
			if (rs.next()) {
				int playerId = rs.getInt(1);
				// Initialize scores for new player
				PreparedStatement scoreStmt = conn.prepareStatement("INSERT INTO scores (player_id, wins, losses, draws) VALUES (?, 0, 0, 0)");
				scoreStmt.setInt(1, playerId);
				scoreStmt.executeUpdate();
				return playerId;
			}
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}
		return -1;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnquit = new javax.swing.JButton();
        btngamestart = new javax.swing.JButton();
        PlayerProfile3 = new javax.swing.JLabel();
        PlayerProfile4 = new javax.swing.JLabel();
        PlayerProfile5 = new javax.swing.JLabel();
        PlayerProfile6 = new javax.swing.JLabel();
        PlayerProfile7 = new javax.swing.JLabel();
        PlayerProfile8 = new javax.swing.JLabel();
        PlayerProfile9 = new javax.swing.JLabel();
        PlayerProfile10 = new javax.swing.JLabel();
        PlayerProfile11 = new javax.swing.JLabel();
        PlayerProfile12 = new javax.swing.JLabel();
        PlayerProfile13 = new javax.swing.JLabel();
        PlayerProfile14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 850));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tic Tac Toe");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 260, 60));

        btnquit.setBackground(new java.awt.Color(0, 0, 0));
        btnquit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnquit.setForeground(new java.awt.Color(255, 255, 255));
        btnquit.setText("Quit");
        btnquit.setBorder(null);
        btnquit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });
        jPanel1.add(btnquit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 170, 40));

        btngamestart.setBackground(new java.awt.Color(0, 0, 0));
        btngamestart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btngamestart.setForeground(new java.awt.Color(255, 255, 255));
        btngamestart.setText("Game Start");
        btngamestart.setBorder(null);
        btngamestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngamestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngamestartActionPerformed(evt);
            }
        });
        jPanel1.add(btngamestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 170, 40));

        PlayerProfile3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        PlayerProfile4.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 770, -1, -1));

        PlayerProfile5.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 440, -1, -1));

        PlayerProfile6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 440, -1, -1));

        PlayerProfile7.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        PlayerProfile8.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        PlayerProfile9.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, -1, -1));

        PlayerProfile10.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        PlayerProfile11.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        PlayerProfile12.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 250, -1, -1));

        PlayerProfile13.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        PlayerProfile14.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\TicTacToe\\src\\main\\java\\com\\tictactoe\\icons\\tic-tac-toe resize.png")); // NOI18N
        jPanel1.add(PlayerProfile14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btngamestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngamestartActionPerformed
        // TODO add your handling code here:
     // Create JDialog for player name input
    JDialog nameDialog = new JDialog(this, "Enter Player Names", true);
    nameDialog.setSize(400, 200);
    nameDialog.setLocationRelativeTo(this);
    nameDialog.setLayout(new GridLayout(4, 2, 10, 10));

    // Input fields
    JLabel playerXLabel = new JLabel("Player X Name:");
    JTextField playerXField = new JTextField(15);
    JLabel playerOLabel = new JLabel("Player O Name:");
    JTextField playerOField = new JTextField(15);
    JButton submitButton = new JButton("Start Game");
    JLabel errorLabel = new JLabel(" ", JLabel.CENTER);
    errorLabel.setForeground(Color.RED);

    nameDialog.add(playerXLabel);
    nameDialog.add(playerXField);
    nameDialog.add(playerOLabel);
    nameDialog.add(playerOField);
    nameDialog.add(new JLabel()); // Spacer
    nameDialog.add(errorLabel);
    nameDialog.add(new JLabel()); // Spacer
    nameDialog.add(submitButton);

    // Submit button action
    submitButton.addActionListener(e -> {
        String playerXName = playerXField.getText().trim();
        String playerOName = playerOField.getText().trim();

        // Validate inputs
        if (playerXName.isEmpty() || playerOName.isEmpty()) {
            errorLabel.setText("Names cannot be blank.");
            return;
        }
        if (!playerXName.matches("[a-zA-Z0-9 ]{1,50}") || !playerOName.matches("[a-zA-Z0-9 ]{1,50}")) {
            errorLabel.setText("Names must be alphanumeric (1-50 chars).");
            return;
        }
        if (playerXName.equalsIgnoreCase(playerOName)) {
            errorLabel.setText("Player names must be different.");
            return;
        }

        // Add or retrieve player IDs from database
        int playerXId = getOrAddPlayer(playerXName);
        int playerOId = getOrAddPlayer(playerOName);
        if (playerXId == -1 || playerOId == -1) {
            errorLabel.setText("Error saving players to database.");
            return;
        }

        // Set player data in GamePage and proceed
        GamePage.setPlayerData(playerXName, playerOName, playerXId, playerOId);
        SwingUtilities.invokeLater(() -> {
            GamePage gamePage = new GamePage();
            gamePage.setVisible(true);
            nameDialog.dispose();
            TicTacToePage.this.dispose();
        });
    });

    nameDialog.setVisible(true);
    }//GEN-LAST:event_btngamestartActionPerformed

    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnquitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerProfile10;
    private javax.swing.JLabel PlayerProfile11;
    private javax.swing.JLabel PlayerProfile12;
    private javax.swing.JLabel PlayerProfile13;
    private javax.swing.JLabel PlayerProfile14;
    private javax.swing.JLabel PlayerProfile3;
    private javax.swing.JLabel PlayerProfile4;
    private javax.swing.JLabel PlayerProfile5;
    private javax.swing.JLabel PlayerProfile6;
    private javax.swing.JLabel PlayerProfile7;
    private javax.swing.JLabel PlayerProfile8;
    private javax.swing.JLabel PlayerProfile9;
    private javax.swing.JButton btngamestart;
    private javax.swing.JButton btnquit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
